# -*- coding: utf-8 -*-
"""Editor de Texto com Análise de Coesão e Coerência.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gs0VGl1EkmGonzrawiQqwxXbZ3wUOduN
"""



"""Nome: Cinéia Spitznagel Pacheco

Editor de Produção textual com Análise de Coesão e Coerência
A atividade foi criada com o objetivo de ajudar meus estudantes na melhoria do
seu texto, como a maior dificuldade deles é conectar as ideias, a coesão e a coe-
rência são fundamentais"""

import re
from collections import Counter

def menu():
    print("\n=== EDITOR DE TEXTO ===")
    print("1. Inserir sua produção textual")
    print("7. Salvar em arquivo .txt")
    print("8. Analisar a coesão e a coerência do meu texto")
    print("0. Sair")
    return input("Escolha uma opção: ")

def salvar_arquivo(texto):
    nome_arquivo = input("Nome do arquivo (sem extensão): ") + ".txt"
    with open(nome_arquivo, "w") as f:
        f.write(texto)
    print(f"Texto salvo em '{nome_arquivo}' com sucesso!")

def analisar_coesao_coerencia(texto):
    print("\n=== ANÁLISE DE COESÃO E COERÊNCIA ===")

    frases = re.split(r'[.!?]', texto)
    frases = [frase.strip() for frase in frases if frase.strip() != '']

    palavras = re.findall(r'\b\w+\b', texto.lower())
    contagem = Counter(palavras)

    conectores = ['portanto', 'além disso', 'porém', 'entretanto', 'então', 'assim', 'contudo', 'todavia']
    conectores_encontrados = [c for c in conectores if c in texto.lower()]

    print(f"- Número de frases: {len(frases)}")

    if frases:
        print(f"- Frase mais curta ({len(min(frases, key=len).split())} palavras): {min(frases, key=len)}")
        print(f"- Frase mais longa ({len(max(frases, key=len).split())} palavras): {max(frases, key=len)}")

    repetidas = [palavra for palavra, freq in contagem.items() if freq > 3 and len(palavra) > 3]
    if repetidas:
        print(f"- Palavras muito repetidas: {', '.join(repetidas)}")
    else:
        print("- Nenhuma repetição excessiva de palavras.")

    if len(conectores_encontrados) < max(1, len(frases)//4):
        print("- Poucos conectores encontrados. Tente usar palavras como: portanto, além disso, porém...")
    else:
        print(f"- Conectores utilizados: {', '.join(conectores_encontrados)}")

    frases_longas = [f for f in frases if len(f.split()) > 20]
    if frases_longas:
        print(f"- Algumas frases estão muito longas. Considere dividi-las para melhorar a clareza.")


"""Texto inicial em branco"""
texto = ""

"""Loop principal"""

while True:
    opcao = menu()

    if opcao == "1":
        texto = input("Digite ou cole uma nova produção textual:\n")
    elif opcao == "7":
        salvar_arquivo(texto)
    elif opcao == "8":
        if texto:
            analisar_coesao_coerencia(texto)
        else:
            print("Nenhuma produção disponível para análise.")
    elif opcao == "0":
        print("Saindo do editor...")
        break
    else:
        print("Opção inválida. Tente novamente.")